#!/usr/bin/env node
const ComplexNumber = require('./complexNumber.js');
const ComplexNumberParser = require('./complexNumberParser.js');

const transformOperand = number => {
  let real, imag;

  [real, imag] = ComplexNumberParser.parse(number);
  [real, imag] = ComplexNumberParser.validateParts(real, imag);

  return new ComplexNumber(real, imag)
};

const command = process.argv[2];

if(command === undefined)
{
  throw new Error('Missing command');
}
else if (command === 'mod')
{
  const number = process.argv[3];
  if (number === undefined)
  {
    throw new Error('Missing number argument');
  }
  else
  {
    const z = transformOperand(number);
    const mod = ComplexNumber.moduo(z);

    console.log(mod);
  }

}
else if (command === 'conj')
{
  const number = process.argv[3];
  if (number === undefined)
  {
    throw new Error('Missing number argument');
  }
  else
  {
    const z = transformOperand(number);

    const conj = ComplexNumber.conjugate(z);

    console.log(conj.toString());
  }

}
else if (command === 'add')
{
  const number1 = process.argv[3];
  const number2 = process.argv[4];
  if (number1 === undefined || number2 === undefined)
  {
    throw new Error('Missing number argument');
  }
  else
  {
    const z1 = transformOperand(number1);
    const z2 = transformOperand(number2);

    const res = ComplexNumber.add(z1, z2);

    console.log(res.toString());
  }
}
else if (command === 'sub')
{
  const number1 = process.argv[3];
  const number2 = process.argv[4];

  if (number1 === undefined || number2 === undefined)
  {
    throw new Error('Missing number argument');
  }
  else
  {
    const z1 = transformOperand(number1);
    const z2 = transformOperand(number2);

    const res = ComplexNumber.subtract(z1, z2);

    console.log(res.toString());
  }

}
else if (command === 'mul')
{
  const number1 = process.argv[3];
  const number2 = process.argv[4];

  if (number1 === undefined || number2 === undefined)
  {
    throw new Error('Missing number argument');
  }
  else
  {
    const z1 = transformOperand(number1);
    const z2 = transformOperand(number2);

    const res = ComplexNumber.multiply(z1, z2);

    console.log(res.toString());
  }
}
else if (command === 'div')
{
  const number1 = process.argv[3];
  const number2 = process.argv[4];

  if (number1 === undefined || number2 === undefined)
  {
    throw new Error('Missing number argument');
  }
  else
  {
    const z1 = transformOperand(number1);
    const z2 = transformOperand(number2);

    const res = ComplexNumber.divide(z1, z2);

    console.log(res.toString());
  }
}
else
{
  throw new Error('Unknown command');
}


